// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd6RwjMsKuDgnHEqHMGTTADSfv8mB5Is8',
    appId: '1:370241594489:web:80f0cc515f3380bedee0a8',
    messagingSenderId: '370241594489',
    projectId: 'task-manger-dac11',
    authDomain: 'task-manger-dac11.firebaseapp.com',
    storageBucket: 'task-manger-dac11.firebasestorage.app',
    measurementId: 'G-MQEMW0DFQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1WmGlGTrJL_iT1-G7uiibhlF8nJH3eu4',
    appId: '1:370241594489:android:4130182137d4755ddee0a8',
    messagingSenderId: '370241594489',
    projectId: 'task-manger-dac11',
    storageBucket: 'task-manger-dac11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMHHS0ESJJNJEFtg7H4Q_0A-_w8W5ng3U',
    appId: '1:370241594489:ios:c980309e2a92c46cdee0a8',
    messagingSenderId: '370241594489',
    projectId: 'task-manger-dac11',
    storageBucket: 'task-manger-dac11.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMHHS0ESJJNJEFtg7H4Q_0A-_w8W5ng3U',
    appId: '1:370241594489:ios:c980309e2a92c46cdee0a8',
    messagingSenderId: '370241594489',
    projectId: 'task-manger-dac11',
    storageBucket: 'task-manger-dac11.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd6RwjMsKuDgnHEqHMGTTADSfv8mB5Is8',
    appId: '1:370241594489:web:83e563d44ea484b9dee0a8',
    messagingSenderId: '370241594489',
    projectId: 'task-manger-dac11',
    authDomain: 'task-manger-dac11.firebaseapp.com',
    storageBucket: 'task-manger-dac11.firebasestorage.app',
    measurementId: 'G-1L0985K24J',
  );
}
